// <auto-generated />
namespace AgilTeamManager.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Versao600 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Versao600));
        
        string IMigrationMetadata.Id
        {
            get { return "201808292323015_Versao 6.00"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
